
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/user
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 1500
      
